# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
DEV:
  ENABLE: True
  TEST_LANG_EMB: './data/clip_step_emb_coin.pth' # used for dim check
TRAIN:
  ENABLE: True
  DATASET: Epickitchens
  BATCH_SIZE: 32 # per machine node
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  LINEAR: False # if False, fully finetuning, including video encoder
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2 # corresponds to FPS 30
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  USE_RAND_AUGMENT: True
EPICKITCHENS:
  VISUAL_DATA_DIR:  "/checkpoints/yiwuzhong/EPIC-Kitchens-100/EPIC-Kitchens-100-videos" # path to video files
  ANNOTATIONS_DIR: "/checkpoints/yiwuzhong/EPIC-Kitchens-100/annotations" # path to dataset annotation
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 30, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
MODEL:
  MODEL_NAME: vit_base_patch16_224_develop
  NUM_CLASSES: 97 # the number of target concepts
  ARCH: vit
  LOSS_FUNC: cross-entropy
  DROPOUT_RATE: 0.5
MIXUP:
  ENABLED: True
  ALPHA: 0.1
TEST:
  ENABLE: True
  DATASET: Epickitchens
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 4 # the number of machine nodes
RNG_SEED: 0
OUTPUT_DIR: .